import {
    LuBrain,
    LuZap,
    LuHeartCrack,
    LuSmile,
    LuHeart,
    LuWind,
    LuPartyPopper,
    LuFlame,
    LuSun,
    LuHistory,
    LuMusic,
    LuDrum,
    LuMic,
    LuDisc,
    LuCpu,
    LuTrees,
    LuRadio,
    LuTreePalm,
    LuMoon,
    LuGlobe,
    LuVolume2,
    LuPenTool,
    LuDumbbell,
    LuCloudRain,
    LuCar,
    LuMoonStar,
    LuCoffee,
    LuLibrary,
    LuGrape,
    LuTent,
    LuFootprints,
    LuUtensils,
    LuGamepad,
    LuSprout,
    LuUsersRound,
    LuPlane,
    LuTimer,
    LuActivity,
    LuYoutube,
} from "react-icons/lu";

export { LuYoutube };

export const moodIcons = {
    focus: LuBrain,
    energy: LuZap,
    sad: LuHeartCrack,
    happy: LuSmile,
    romance: LuHeart,
    chill: LuWind,
    party: LuPartyPopper,
    angry: LuFlame,
    spiritual: LuSun,
    nostalgia: LuHistory,
};

export const genreIcons = {
    alternative: LuVolume2,
    blues: LuMusic,
    classical: LuLibrary,
    country: LuTent,
    dance: LuDisc,
    electronic: LuCpu,
    folk: LuTrees,
    gospel: LuSun,
    hiphop: LuMic,
    jazz: LuWind,
    latin: LuFlame,
    metal: LuZap,
    newage: LuMoon,
    pop: LuRadio,
    reggae: LuTreePalm,
    rnb: LuDrum,
    rock: LuVolume2,
    singer: LuPenTool,
    world: LuGlobe,
};

// Map emojis in "best_for" to icons
export const emojiToIcon = {
    "😤": LuFlame,
    "🏋️": LuDumbbell,
    "🌧️": LuCloudRain,
    "🚗": LuCar,
    "💔": LuHeartCrack,
    "🌃": LuMoonStar,
    "☕": LuCoffee,
    "🎙️": LuMic,
    "📚": LuLibrary,
    "🧘": LuBrain,
    "🍷": LuGrape,
    "😴": LuMoon,
    "🌾": LuSprout,
    "🔥": LuFlame,
    "💃": LuFootprints,
    "🏡": LuHistory,
    "🎉": LuPartyPopper,
    "🏃": LuTimer,
    "🌅": LuSun,
    "⚡": LuZap,
    "💻": LuCpu,
    "🌙": LuMoon,
    "🧠": LuBrain,
    "🕺": LuFootprints,
    "🌿": LuTrees,
    "📖": LuLibrary,
    "👨👩👧": LuUsersRound,
    "🌄": LuSun,
    "🤲": LuBrain,
    "💪": LuActivity,
    "🫂": LuUsersRound,
    "🧹": LuWind,
    "🖌️": LuPenTool,
    "✍️": LuPenTool,
    "🍽️": LuUtensils,
    "🌞": LuSun,
    "❤️": LuHeart,
    "🍜": LuUtensils,
    "🧩": LuBrain,
    "🎮": LuGamepad,
    "💆": LuCloudRain,
    "🌊": LuWind,
    "😊": LuSmile,
    "🏖️": LuTreePalm,
    "😌": LuWind,
    "🤝": LuUsersRound,
    "🛁": LuCloudRain,
    "🗺️": LuGlobe,
    "✈️": LuPlane,
};
